name: "Make JSON from releases"
author: "Igor Pecovnik"
description: "Make JSON from releases"
runs:
  using: "composite"
  steps:

    - name: Install dependencies
      shell: bash      
      run: |

        sudo npm install --location=global json || true
        gh release list | awk '{print $1}'
