name: "Make JSON from releases"
author: "Igor Pecovnik"
description: "Make JSON from releases"
inputs:
  choice:
    filename: Filename
    required: true
runs:
  using: "composite"
  steps:

    - name: Install dependencies
      shell: bash      
      run: |

        echo ${{ inputs.filename }}
        sudo npm install --location=global json || true
        gh release list | awk '{print $1}'
