
name: "Build list"
description: ""
runs:
  using: "composite"
  steps:
    - name: "Build images"
      id: build-images
      run: |
        string=($(find config/boards/ -mindepth 1 -maxdepth 1 -type f -name "*.csc" 2> /dev/null | sort | cut -d"/" -f3 | cut -d"." -f1))
        branch=("current")
        release=("jammy" "sid")
        de=("cli" "xfce")
        m="3dsupport,browsers,chat,desktop_tools,editors,email,internet,multimedia,office,programming,remote_desktop"
        for j in ${string[@]}
        do
          for k in ${release[@]}
          do
            for i in ${branch[@]}
            do
              for l in ${de[@]}
              do
	            if [[ $l == cli ]]; then
                l="       "
		            m=""
		          else
		            m="3dsupport,browsers,chat,desktop_tools,editors,email,internet,multimedia,office,programming,remote_desktop"
	            fi
              echo "$j    $i    $k    $l    $m"
              done
            done
          done
        done
      shell: bash
