
name: "Build list"
description: ""
inputs:
  type:
    description: "conf,csc,tvb"
    required: true
runs:
  using: "composite"
  steps:
    - name: "Build images"
      id: build-images
      run: |
        truncate targets.txt --size=0
        truncate boards.txt --size=0
        string=($(find build/config/boards/ -mindepth 1 -maxdepth 1 -type f -name "*.${{ inputs.type }}" 2> /dev/null | sort | cut -d"/" -f4 | cut -d"." -f1))
        release=("jammy" "sid")
       
        for j in ${string[@]}
        do
          for k in ${release[@]}
          do
            branch="current"
            KERNEL=$(cat build/config/boards/$j.${{ inputs.type }} | grep KERNEL_TARGET)
            DESKTOP=$(cat build/config/boards/$j.csc | grep BUILD_DESKTOP)
            if [[ -z "$(echo $KERNEL | grep $branch)" ]]; then
                branch=$(echo "$KERNEL" | sed 's/"//g' | cut -d"=" -f2)
            fi
            if [[ -n "$(echo $DESKTOP | grep no)" ]]; then
            de=("cli")
            else
            de=("cli" "xfce")
            fi
              for l in ${de[@]}
              do
                if [[ $l == cli ]]; then         
                l="cli     "
                m=""
                else
                l="desktop"
                m=" xfce config_base 3dsupport,browsers,chat,desktop_tools,editors,email,internet,multimedia,office,programming,remote_desktop"
                fi
              echo "$j" >> boards.txt
            done
          done
        done
      shell: bash
