
name: "Build list"
description: ""
inputs:
  type:
    description: "conf,csc,tvb"
    required: true
runs:
  using: "composite"
  steps:
    - name: "Build images"
      id: build-images
      run: |
        truncate targets.txt --size=0
        truncate boards.txt --size=0
        string=($(find build/config/boards/ -mindepth 1 -maxdepth 1 -type f -name "*.${{ inputs.type }}" 2> /dev/null | sort | cut -d"/" -f4 | cut -d"." -f1))
        branch=("current")
        release=("jammy" "sid")
        de=("cli" "xfce")
        m="3dsupport,browsers,chat,desktop_tools,editors,email,internet,multimedia,office,programming,remote_desktop"
        for j in ${string[@]}
        do
          for k in ${release[@]}
          do
            for i in ${branch[@]}
            do
              for l in ${de[@]}
              do
                if [[ $l == cli ]]; then         
                l="cli     "
                m=""
                else
                l="desktop"
                m="3config_base  dsupport,browsers,chat,desktop_tools,editors,email,internet,multimedia,office,programming,remote_desktop"
                fi
              echo "$j    $i    $k    $l  stable  yes $m" >> targets.txt
              echo "$j" >> boards.txt
             done
            done
          done
        done
      shell: bash
