name: "Get latest cache version"
author: "Igor Pecovnik"
description: "Get latest cache version"
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
        repository: armbian/cache
        path: cache
        clean: false
        
    - name: "Get last release version from cache"
      id: check-released
      shell: bash
      run: |
        
        echo "ROOTFSCACHE_VERSION=$(cd cache;gh release list --exclude-drafts | awk '{print $(NF-1)}')" >> $GITHUB_ENV
