name: "Enable Hetzner VMs"
author: "Igor Pecovnik"
inputs:
  KEY_POWER_ON:
    required: true
  KNOWN_HOSTS_REPOSITORY:
    required: true
  USER_REPOSITORY:
    required: true
  HOST_REPOSITORY:
    required: true
runs:
  using: "composite"
  steps:

    - name: "Install dependencies"      
      shell: bash
      run: |
        echo "Install"
