name: "Enable Hetzner VMs"
author: "Igor Pecovnik"
inputs:
  machine-name:
    required: true
  machine-type:
    required: true
  key:
    required: true
  known_hosts:
    required: true
  hetzner_id:
    required: true
  github_token:
    required: true

runs:
  using: "composite"
  env:
    HCLOUD_TOKEN: ${{ inputs.hetzner_id }}
    GH_TOKEN: ${{ inputs.github_token }}
  steps:

    - name: "Install dependencies ${{ inputs.machine-type }} ${{ inputs.machine-name }}"
      shell: bash
      run: |
        echo "Install ${{ inputs.machine-type }} ${{ inputs.machine-name }}"

    - name: Install SSH key for storage
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ inputs.key }}
        known_hosts: ${{ inputs.known_hosts }}
        if_key_exists: replace

    - name: Install Homebrew
      shell: bash
      run: |
          sudo apt-get -y install wamerican
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          (echo; echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"') >> ${HOME}/.bash_profile
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew install hcloud
          
          # generate machine
          #MACHINE_NAME=$(shuf -n1 /usr/share/dict/american-english | sed "s/[^[:alnum:]-]//g" | sed 's/./\L&/g')
          #hcloud server create --name ${MACHINE_NAME} --image ubuntu-22.04 --type cax11 --ssh-key TORRENT
          #sleep 30
          hcloud server list
