name: "Enable Hetzner VMs"
author: "Igor Pecovnik"
inputs:
  machine-name:
    required: true
  machine-type:
    required: true
runs:
  using: "composite"
  steps:

    - name: "Install dependencies ${{ inputs.machine-type }} ${{ inputs.machine-name }}"
      shell: bash
      run: |
        echo "Install ${{ inputs.machine-type }} ${{ inputs.machine-name }}"
