name: "Build Armbian images"
description: ""
inputs:
  choice:
    description: Build targets
    required: true
  runner:
    description: Build runners for CLI
    required: true
  sourcerepo:
    description: Source repository
    required: true
  packagesrepo:
    description: Beta packages repository
    required: true
  advanced:
    description: 'Single board (grep -w tinkerboard |)'
    required: true
runs:
  using: "composite"
  steps:
    - name: "Build images"
      id: build-images
      run: |
        echo "Test"
      shell: bash

cli1:
  uses: armbian/scripts/.github/workflows/build-with-docker.yml@master

  with:

    variant: 'cli:${{ inputs.choice }}'
    sourcerepo: '${{ inputs.sourcerepo }}'
    packagesrepo: '${{ inputs.packagesrepo }}'     
    runner: '${{ inputs.runner }}'
    part: 1
    of: 2
    include: '${{ inputs.advanced }}'
    exclude: 'grep -v uefi-x86 | '
    uploading: false

  secrets:
    GPG_KEY1: ${{ secrets.GPG_KEY1 }}
    GPG_PASSPHRASE1: ${{ secrets.GPG_PASSPHRASE1 }}
    GPG_KEY2: ${{ secrets.GPG_KEY2 }}
    GPG_PASSPHRASE2: ${{ secrets.GPG_PASSPHRASE2 }}
    SCRIPTS_ACCESS_TOKEN: ${{ secrets.SCRIPTS_ACCESS_TOKEN }}
    SSH_KEY_TORRENTS: ${{ secrets.KEY_TORRENTS }}
    KNOWN_HOSTS_UPLOAD: ${{ secrets.KNOWN_HOSTS_UPLOAD }}
