name: "Build Armbian images"
description: ""
inputs:
  choice:
    description: Build targets
    required: true
  runner:
    description: Build runners for CLI
    required: true
  sourcerepo:
    description: Source repository
    required: true
  packagesrepo:
    description: Beta packages repository
    required: true
  advanced:
    description: 'Single board (grep -w tinkerboard |)'
    required: true
runs:
  using: "composite"
  steps:
    - uses: armbian/scripts/.github/workflows/build-with-docker.yml@master
      with:
        variant: 'cli:${{ inputs.choice }}'
        sourcerepo: '${{ inputs.sourcerepo }}'
        packagesrepo: '${{ inputs.packagesrepo }}'     
        runner: '${{ inputs.runner }}'
        part: 1
        of: 2
        include: '${{ inputs.advanced }}'
        exclude: 'grep -v uefi-x86 | '
        uploading: false
