name: "Runner prepare"
author: "Igor Pecovnik"
description: "Cleaning self hosted runners"
inputs:
  KEY_POWER_ON:
    description: SSH key for power server
    required: true
runs:
  using: "composite"
  steps:

    - name: Install SSH key for repository
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.KEY_POWER_ON }}
        name: ${{ inputs.KEY_ID }}
        known_hosts: ${{ secrets.KNOWN_HOSTS_REPOSITORY }}
        if_key_exists: replace

    - name: Update repository
      shell: bash
      run: |
        
        if: ${{ github.repository_owner == 'Armbian' && env.SKIP != 'yes' }}
        run: ssh -T -i ~/.ssh/${{ inputs.KEY_ID }} ${{ secrets.USER_REPOSITORY }}@${{ secrets.HOST_REPOSITORY }}
