name: "Runner prepare"
author: "Igor Pecovnik"
description: "Cleaning self hosted runners"
runs:
  using: "composite"
  steps:

    - name: Update index and upgrade
      shell: bash      
      run: |

        # unath should be removed asap
        if [[ $(curl -s http://ifconfig.me) == "93.103.15.56" ]]; then
        sudo rm -f /etc/apt/sources.list.d/githubcli.list
        sudo apt-get -y --allow-unauthenticated update || true
        sudo apt-get -y --allow-unauthenticated upgrade || true
        sudo apt-get -y --allow-unauthenticated autoremove || true
        fi

    - name: Clean folders
      shell: bash      
      run: |

        sudo rm -rf build/userpatches/* || true
        sudo rm -rf build/.tmp/ || true
        [[ -f "changes" ]] && sudo rm -rf changes 2>/dev/null || true
        #[[ -f "$HOME/.ssh/known_hosts" ]] && sudo rm "$HOME/.ssh/known_hosts" || true

        # umount all our mounts
        WORKSPACE=$(echo ${{ github.workspace }} | rev | cut -d"/" -f3- | rev)
        echo $WORKSPACE
        sudo mount | grep $WORKSPACE | cut -d" " -f3 || true
        sudo mount | grep $WORKSPACE | grep -E toolchain\|rootfs | cut -d" " -f3 | xargs sudo umount || true
        
        sudo find $WORKSPACE -mindepth 1 -maxdepth 1 -type d ! -name "build" ! -name "_*" ! -name "$(echo ${{ github.workspace }} | rev | cut -d"/" -f2 | rev)" -exec sudo rm -rf {} + || true
        sudo rm -rf $WORKSPACE/build/output/debs/* $WORKSPACE/build/output/debs-beta/* /var/log/journal || true
        sudo rm -rf $WORKSPACE/build/cache $WORKSPACE/build/output/images/* || true
        
