name: "Runner prepare"
author: "Igor Pecovnik"
description: "Cleaning self hosted runners"
runs:
  using: "composite"
  steps:

    - name: Update index and upgrade
      shell: bash      
      run: |

        echo ${{ github.runner }}
        echo ${{ github.runner_arch }}

        # unath should be removed asap
        #if [[ $(curl -s http://ifconfig.me) == "93.103.15.56" ]]; then
        #sudo rm -f /etc/apt/sources.list.d/githubcli.list        
        #sudo apt-get -y --allow-unauthenticated update || true        
        #sudo apt-get -y --allow-unauthenticated upgrade || true
        #sudo apt-get -y --allow-unauthenticated autoremove || true
        #sudo apt-get -y --allow-unauthenticated install buildtorrent
        #fi
        # install lftp
        if ! command -v "lftp" > /dev/null 2>&1; then
        sudo apt-get install "lftp" -y
        fi
        
        # fix docker permissions
        #sudo usermod -aG docker $USER || true
        #newgrp docker

    - name: Clean folders
      shell: bash      
      run: |

        # umount all our mounts
        echo ${{ github.workspace }}
        sudo mountpoint -q ${{ github.workspace }}/build/cache/utility && sudo umount ${{ github.workspace }}/build/cache/utility || true
        sudo mountpoint -q ${{ github.workspace }}/build/cache/toolchain && sudo umount ${{ github.workspace }}/build/cache/toolchain || true
        sudo mountpoint -q ${{ github.workspace }}/build/output/debs && sudo umount ${{ github.workspace }}/build/output/debs
        sudo mountpoint -q ${{ github.workspace }}/build/output/debs-beta && sudo umount ${{ github.workspace }}/build/output/debs-beta
        sudo mountpoint -q ${{ github.workspace }}/build/cache/rootfs && sudo umount ${{ github.workspace }}/build/cache/rootfs
        sudo mountpoint -q ${{ github.workspace }}/build/cache/rootfs.upload && sudo umount ${{ github.workspace }}/build/cache/rootfs.upload
        #
        sudo umount ${{ github.workspace }}/build/output/debs-beta || true
        sudo umount ${{ github.workspace }}/build/output/debs || true
                
        # fix permission
        sudo chown -R ${USER}.${USER} ${{ github.workspace }} || true
        
        # them remove what we don't need
        sudo rm -rf ${{ github.workspace }}/build/cache/ || true
        
        ! sudo mountpoint -q ${{ github.workspace }}/build/output/debs && sudo rm -rf ${{ github.workspace }}/build/output/debs || true
        ! sudo mountpoint -q ${{ github.workspace }}/build/output/debs-beta && sudo rm -rf ${{ github.workspace }}/build/output/debs-beta || true
        
        sudo rm -rf ${{ github.workspace }}/build/userpatches/* || true
        sudo rm -rf ${{ github.workspace }}/build/.tmp/ || true        
        sudo rm -rf changes 2>/dev/null || true
        
        # remove all but current
        PROJECT=$(echo ${{ github.workspace }} | rev | cut -d'/' -f 1 | rev)
        cd ..
        cd ..
        sudo find . -name "toolchain" -exec sudo umount {} + || true
        sudo find $(echo ${{ github.workspace }} | rev | cut -d"/" -f3- | rev) -mindepth 1 -maxdepth 1 ! -name "_*" ! -name ${PROJECT} -exec sudo rm -rf {} + || true
