name: "Runner prepare"
author: "Igor Pecovnik"
description: "Cleaning self hosted runners"
runs:
  using: "composite"
  steps:

    - name: Update index and upgrade
      shell: bash      
      run: |

        # unath should be removed asap
        sudo apt-get -y --allow-unauthenticated update || true
        sudo apt-get -y --allow-unauthenticated upgrade || true
        sudo apt-get -y --allow-unauthenticated autoremove || true

    - name: Clean folders
      shell: bash      
      run: |

        [[ -f "changes" ]] && sudo rm -rf changes 2>/dev/null || true
        #[[ -f "$HOME/.ssh/known_hosts" ]] && sudo rm "$HOME/.ssh/known_hosts" || true

        # umount all our mounts
        WORKSPACE=$(echo ${{ github.workspace }} | rev | cut -d"/" -f3- | rev)
        sudo mount | grep $WORKSPACE | cut -d" " -f3 || true
        sudo mount | grep $WORKSPACE | cut -d" " -f3 | xargs sudo umount || true
        
        sudo find $WORKSPACE -mindepth 1 -maxdepth 1 -type d ! -name "build" ! -name "_*" ! -name "$(echo ${{ github.workspace }} | rev | cut -d"/" -f2 | rev)" -exec sudo rm -rf {} + || true
        sudo rm -rf $WORKSPACE/build/build/build/cache/ccache $WORKSPACE/build/build/build/cache/rootfs || true
        sudo rm -rf $WORKSPACE/build/output/debs/* $WORKSPACE/build/output/debs-beta/* /var/log/journal || true
        sudo rm -rf $WORKSPACE/build/cache/hash/* $WORKSPACE/build/cache/hash-beta/* $WORKSPACE/build/output/images/* || true
