name: "Runner prepare"
author: "Igor Pecovnik"
description: "Cleaning self hosted runners"
runs:
  using: "composite"
  steps:

    - name: Update index and upgrade
      shell: bash      
      run: |

        # unath should be removed asap
        if [[ $(curl -s http://ifconfig.me) == "93.103.15.56" ]]; then
        sudo rm -f /etc/apt/sources.list.d/githubcli.list
        while sudo fuser /var/{lib/{dpkg,apt/lists},cache/apt/archives}/lock >/dev/null 2>&1; do sleep 1; done
        sudo apt-get -y --allow-unauthenticated update || true
        while sudo fuser /var/{lib/{dpkg,apt/lists},cache/apt/archives}/lock >/dev/null 2>&1; do sleep 1; done
        sudo apt-get -y --allow-unauthenticated upgrade || true
        while sudo fuser /var/{lib/{dpkg,apt/lists},cache/apt/archives}/lock >/dev/null 2>&1; do sleep 1; done
        sudo apt-get -y --allow-unauthenticated autoremove || true
        fi
        while sudo fuser /var/{lib/{dpkg,apt/lists},cache/apt/archives}/lock >/dev/null 2>&1; do sleep 1; done
        sudo apt-get -y --allow-unauthenticated install buildtorrent

    - name: Clean folders
      shell: bash      
      run: |

        # umount all our mounts
        sudo mountpoint -q ${{ github.workspace }}/build/cache/utility && sudo umount ${{ github.workspace }}/build/cache/utility || true
        sudo mountpoint -q ${{ github.workspace }}/build/cache/toolchain && sudo umount ${{ github.workspace }}/build/cache/toolchain || true
        sudo mountpoint -q ${{ github.workspace }}/build/output/debs && sudo umount ${{ github.workspace }}/build/output/debs || true
        sudo mountpoint -q ${{ github.workspace }}/build/output/debs-beta && sudo umount ${{ github.workspace }}/build/output/debs-beta || true
        sudo mountpoint -q ${{ github.workspace }}/build/cache/rootfs && sudo umount ${{ github.workspace }}/build/cache/rootfs || true
        sudo mountpoint -q ${{ github.workspace }}/build/cache/rootfs.upload && sudo umount ${{ github.workspace }}/build/cache/rootfs.upload || true
                
        # fix permission
        sudo chown -R ${USER}.${USER} ${{ github.workspace }}/build/output/ || true
        
        # them remove what we don't need
        sudo rm -rf ${{ github.workspace }}/build/cache/ || true
        
        ! sudo mountpoint -q ${{ github.workspace }}/build/output/debs && sudo rm -rf ${{ github.workspace }}/build/output/debs || true
        ! sudo mountpoint -q ${{ github.workspace }}/build/output/debs-beta && sudo rm -rf ${{ github.workspace }}/build/output/debs-beta || true
        
        sudo rm -rf ${{ github.workspace }}/build/userpatches/* || true
        sudo rm -rf ${{ github.workspace }}/build/.tmp/ || true        
        sudo rm -rf changes 2>/dev/null || true
        
        # remove all but current
        PROJECT=$(echo ${{ github.workspace }} | rev | cut -d'/' -f 1 | rev)
        cd ..
        cd ..
        sudo find $(echo ${{ github.workspace }} | rev | cut -d"/" -f3- | rev) -mindepth 1 -maxdepth 1 ! -name "_*" ! -name ${PROJECT} -exec sudo rm -rf {} + || true       
