name: "Runner clening"
author: "Igor Pecovnik"
description: "Cleaning self hosted runners"
runs:
  using: "composite"
  steps:

      - name: Remove dangling Docker images
        shell: bash 
        run: |

          sudo docker image prune -a --force

      - name: Upgrade
        shell: bash 
        run: |

          # install package aptdaemon
          sudo aptdcon --safe-upgrade

      - name: Remove Other projects
        shell: bash 
        run: |

          cd ../..
          # remove all
          sudo find $(echo ${{ github.workspace }} | rev | cut -d"/" -f3- | rev) \
          -mindepth 1 -maxdepth 1 ! -name "_*" -exec sudo rm -rf {} + || true
