name: "Runner clening"
author: "Igor Pecovnik"
description: "Cleaning self hosted runners"
runs:
  using: "composite"
  steps:

      - name: "Fix permissions"
        shell: bash 
        run: |
          env
          sudo chown -R $USER.$USER . || true

      - name: Remove dangling Docker images
        shell: bash 
        run: |

          sudo docker image prune -a --force || true

      - name: Upgrade
        shell: bash 
        run: |

          sudo DEBIAN_FRONTEND=noninteractive apt-get -o DPkg::Lock::Timeout=600 -yqq update
          sudo DEBIAN_FRONTEND=noninteractive apt-get -o DPkg::Lock::Timeout=600 -yqq upgrade
          sudo DEBIAN_FRONTEND=noninteractive apt-get -o DPkg::Lock::Timeout=600 -yqq autoremove
          sudo DEBIAN_FRONTEND=noninteractive apt-get -o DPkg::Lock::Timeout=600 -yqq clean

      - name: Remove Other projects
        shell: bash 
        run: |

          cd ../..
          PROJECT=$(echo ${{ github.workspace }} | rev | cut -d'/' -f 1 | rev)
          sudo find $(echo ${{ github.workspace }} | rev | cut -d"/" -f3- | rev) \
          -mindepth 1 -maxdepth 1 ! -name "_*" ! -name ${PROJECT} -exec sudo rm -rf {} + || true
