name: "Runner clening"
author: "Igor Pecovnik"
description: "Cleaning self hosted runners"
runs:
  using: "composite"
  steps:

      - name: "Fix permissions"
        if: ${{ env.RUNNER_USER != runner }}
        shell: bash 
        run: |
        
          sudo chown -R $USER.$USER . || true

      - name: Remove dangling Docker images
        if: ${{ env.RUNNER_USER != runner }}
        shell: bash 
        run: |

          sudo docker image prune -a --force || true

      - name: Remove Other projects
        if: ${{ env.RUNNER_USER != runner }}
        shell: bash 
        run: |

          cd ../..
          PROJECT=$(echo ${{ github.workspace }} | rev | cut -d'/' -f 1 | rev)
          sudo find $(echo ${{ github.workspace }} | rev | cut -d"/" -f3- | rev) \
          -mindepth 1 -maxdepth 1 ! -name "_*" ! -name ${PROJECT} -exec sudo rm -rf {} + || true
